### ISSUE TITLE
redirectUri strips URL parameters

### ISSUE THREAD

**Issue by amityweb** [infusionsoft/infusionsoft-php#117]
My redirect URL will be the format:
`http://mydomain.co.uk/wp-admin/options-general.php?page=infusionsoft-admin`
but upon redirect it ends up:
`http://mydomain.co.uk/wp-admin/options-general.php?scope=full%7Cdz368.infusionsoft.com&code=xxxxxxxxxxxxxx`

As you can see page=infusionsoft-admin is stripped out. This means my plugin page wont load, and so I cannot execute further code. I need the redirect URL to include page=infusionsoft-admin, so how can I do this please?

**Comment by micfai** [comment]
We currently don't support url parameters in the redirect uri. Since you are using WordPress, you can hook into the init function and check and see if the `code` and `scope` parameters are set and if they are, then perform your other code execution to request the access token and save it.

However if you plan on making this plugin for public consumption then you should really look at implementing a proxy to handle the token retrievals so you can protect your keys.

**Comment by amityweb** [comment]
Yes thats kind of what I am doing. I have to check on every page load if code and scope exist, so its not the best way, but seems to be the only way. 

Not sure I understand the public consumption and key protection part. I am not intending to release this plugin, it is for a specific customer. But even if I did, I would not supply my own keys, the plugin has settings fields to enter specific keys for the website/customer. 

Thanks
