### ISSUE TITLE
"Authorization code is invalid"

### ISSUE THREAD

**Issue by crazyserb** [infusionsoft/infusionsoft-php#122]
I dunno what and why, but I can't even get authorized to get a token with this script to begin with... 

I literally took the addWithDupCheck.php sample, plugged in our clientId, clientSecret and redirectUri, enabled cURL instead of Guzzle (as Guzzle was giving us 500 errors), and now after that popup window to authorize the app, once it gets back to redirectUri all we get is this:

http://prntscr.com/f73nno

(it's just a print_r($infusionsoft->requestAccessToken($_GET['code'])) 

Any ideas? 

Totally have no clue where to even begin to debug this and how, when we can't even get past the 1st step.

What did I miss?!

Was I supposed to add that redirectUri somewhere else in our account, to authorize it to receive tokens or something? Or.... what?

**Comment by crazyserb** [comment]
Tsk, never mind... had to re-login into that browser session into my InfusionSoft account to actually be able to authorize things properly. Weird, but... whatever. Kinda sorta works now.

Off to the next step...

**Comment by crazyserb** [comment]
Ok, step 2 - problem again.

In that sample file provided, the line:
`		try {
			$cid = $infusionsoft->contacts()->where('email', $email)->first();`

returns the following error in error_log:

PHP Fatal error:  Call to undefined method Infusionsoft\Api\ContactService::::where() in /home/site/public_html/isoft.php on line 52

Ugh... what is this due to?

What am I missing now?

**Comment by micfai** [comment]
@crazyserb I am assuming you just copied/pasted the addWithDupCheck.php sample to a new file?

The error you are getting is saying you are trying to use REST api functions with xmlrpc classes. If you modified infusionsoft.php file to default the contact service to xmlrpc then you will get this issue since xmlrpc functions are different.

I suggest using the REST api as much as possible since the xmlrpc api is considered legacy.
