### ISSUE TITLE
Client error response [status code] 400 [reason phrase] Bad Request

### ISSUE THREAD

**Issue by merlindiavova** [infusionsoft/infusionsoft-php#16]
When it's time to refresh the token I receive the error below. I know sometimes the there is a connection error with infusionsoft so i retry a few times but it does not help. can you advise on what I'm missing here?

exception 'Guzzle\Http\Exception\ClientErrorResponseException' with message 'Client error response [status code] 400 [reason phrase] Bad Request [url] https://api.infusionsoft.com/token' in /home/zae/app/vendor/guzzle/guzzle/src/Guzzle/Http/Exception/BadResponseException.php:43 Stack trace: #0 /home/zae/app/vendor/guzzle/guzzle/src/Guzzle/Http/Message/Request.php(145): Guzzle\Http\Exception\BadResponseException::factory(Object(Guzzle\Http\Message\EntityEnclosingRequest), Object(Guzzle\Http\Message\Response)) #1 [internal function]: Guzzle\Http\Message\Request::onRequestError(Object(Guzzle\Common\Event), 'request.error', Object(Symfony\Component\EventDispatcher\EventDispatcher)) #2 /home/zae/app/vendor/symfony/event-dispatcher/Symfony/Component/EventDispatcher/EventDispatcher.php(164): call_user_func(Array, Object(Guzzle\Common\Event), 'request.error', Object(Symfony\Component\EventDispatcher\EventDispatcher)) #3 /home/zae/app/vendor/symfony/event-dispatcher/Symfony/Component/EventDispatcher/EventDispatcher.php(53): Symfony\Component\EventDispatcher\EventDispatcher->doDispatch(Array, 'request.error', Object(Guzzle\Common\Event)) #4 /home/zae/app/vendor/guzzle/guzzle/src/Guzzle/Http/Message/Request.php(589): Symfony\Component\EventDispatcher\EventDispatcher->dispatch('request.error', Object(Guzzle\Common\Event)) #5 /home/zae/app/vendor/guzzle/guzzle/src/Guzzle/Http/Message/Request.php(378): Guzzle\Http\Message\Request->processResponse(Array) #6 /home/zae/app/vendor/guzzle/guzzle/src/Guzzle/Http/Message/EntityEnclosingRequest.php(49): Guzzle\Http\Message\Request->setState('complete', Array) #7 /home/zae/app/vendor/guzzle/guzzle/src/Guzzle/Http/Curl/CurlMulti.php(286): Guzzle\Http\Message\EntityEnclosingRequest->setState('complete', Array) #8 /home/zae/app/vendor/guzzle/guzzle/src/Guzzle/Http/Curl/CurlMulti.php(244): Guzzle\Http\Curl\CurlMulti->processResponse(Object(Guzzle\Http\Message\EntityEnclosingRequest), Object(Guzzle\Http\Curl\CurlHandle), Array) #9 /home/zae/app/vendor/guzzle/guzzle/src/Guzzle/Http/Curl/CurlMulti.php(227): Guzzle\Http\Curl\CurlMulti->processMessages() #10 /home/zae/app/vendor/guzzle/guzzle/src/Guzzle/Http/Curl/CurlMulti.php(211): Guzzle\Http\Curl\CurlMulti->executeHandles() #11 /home/zae/app/vendor/guzzle/guzzle/src/Guzzle/Http/Curl/CurlMulti.php(105): Guzzle\Http\Curl\CurlMulti->perform() #12 /home/zae/app/vendor/guzzle/guzzle/src/Guzzle/Http/Curl/CurlMultiProxy.php(91): Guzzle\Http\Curl\CurlMulti->send() #13 /home/zae/app/vendor/guzzle/guzzle/src/Guzzle/Http/Client.php(282): Guzzle\Http\Curl\CurlMultiProxy->send() #14 /home/zae/app/vendor/guzzle/guzzle/src/Guzzle/Http/Message/Request.php(198): Guzzle\Http\Client->send(Object(Guzzle\Http\Message\EntityEnclosingRequest)) #15 /home/zae/app/vendor/infusionsoft/php-sdk/src/Infusionsoft/Http/GuzzleClient.php(35): Guzzle\Http\Message\Request->send() #16 /home/zae/app/vendor/infusionsoft/php-sdk/src/Infusionsoft/Infusionsoft.php(266): Infusionsoft\Http\GuzzleClient->request('https://api.inf...', Array, Array, 'POST') #17 /home/zae/app/_a/libraries/Infusionsoft.php(78): Infusionsoft\Infusionsoft->refreshAccessToken() #18 /home/zae/app/_a/libraries/Infusionsoft.php(88): Infusionsoft::_refreshTokenWithAction('webForms', 'getMap', Array) #19 /home/zae/app/_a/libraries/Infusionsoft.php(88): Infusionsoft::_refreshTokenWithAction('webForms', 'getMap', Array) #20 /home/zae/app/_a/libraries/Infusionsoft.php(88): Infusionsoft::_refreshTokenWithAction('webForms', 'getMap', Array) #21 /home/zae/app/_a/libraries/Infusionsoft.php(50): Infusionsoft::_refreshTokenWithAction('webForms', 'getMap', Array) #22 /home/zae/app/_a/libraries/Infusionsoft.php(35): Infusionsoft::_execute('webForms', 'getMap') #23 /home/zae/app/_a/controllers/admin/Sync/Index.php(39): Infusionsoft::getWebforms() #24 [internal function]: Index->select() #25 /home/zae/app/_s/core/Zae.php(514): call_user_func_array(Array, Array) #26 /home/zae/app/public/index.php(309): require_once('/home/zae/app...') #27 {main}

**Comment by micfai** [comment]
This usually happens when you have a bad refresh token. Are you getting this on a consistent basis?

**Comment by merlindiavova** [comment]
Yes, if the token expires and I try to refresh it this is the error i get back. Whilst I was waiting for your response I added refresh the token call before every api call and for the last couple of hours it's been smooth sailing

**Comment by micfai** [comment]
In Issue #18 you said the CurlClient seems to work better for you. Since you have moved to the CurlClient, are you getting this response anymore?

**Comment by merlindiavova** [comment]
So it's weird, When I want to refresh the token the CurlClient works better. When i need to make an API call the Guzzle Client works better. So in my code my refreshToken method sets the http client to Curl and once the refresh token has been successfully stored I then set the http client back to Guzzle.
Weird huh?

I'm going to try this out on another server/host later this evening and let you know the results.

**Comment by kressaty** [comment]
@merlindiavova do you use runscope by any chance? If you can, run your request through runscope's traffic inspector and then email me a link to the (failed) request (you can share them with a unique link) to jonathan at vuurr dot com - we're trying to work through this and get a solution pushed to the library asap.

**Comment by merlindiavova** [comment]
@kressaty  Sorry for my delayed reply. I will setup a runscope account and email you over the details.

**Comment by merlindiavova** [comment]
@kressaty I have tried this with runscope and it runs ok.

I'm still however experiencing errors hwen the token has expired and I need to refresh it. 

I tried refreshing the token on every call just to see and yup if you make two consecutive call it then it  return an error and then you have to re-authenticate. 

I have tried refreshing the token every 2-4 calls and it seems better BUT as you can appreciate if I have an that runs crons every 30min to sync details it will fail and wait for the user to re-authenticate.

Any ideas?

**Comment by kressaty** [comment]
So when you run it through Runscope, it always works? The reason I want to see it failed in Runscope is so we can track down a root cause on the backend. (Excuse brevity, I'm mobile)

**Comment by merlindiavova** [comment]
I'm a runscope noob so I'm in sure how to test access token refreshes.

This I believe could be the main issue.

**Comment by kressaty** [comment]
So you'll want to use their traffic inspector, and it's going to give you an id. You'll use that and set a new Token URI, using ```$infusionsoft->setTokenUri($url)```, and your url will be ```https://api-infusionsoft-com-RUNSCOPEKEY.runscope.net/token```

From there, you can share that request that shows up in the Runscope traffic inspector and then send me the public link in a private email.

**Comment by merlindiavova** [comment]
@kressaty so I've done as you described previously and all seems well. I could not  find your email address so maybe email me and I will reply back. 

One thing that strikes me as odd is that every call i get the TokenExpiredException and as I have my code blocks wrapped in a try n catch i refresh the token but this is happening on every call? Is that normal. 

see my code below

       <?php

        $infst = Social::getInfusionsoft();

        $infstToken = new \Infusionsoft\Token(
            [
                'access_token' => $infst->oauth2_access_token,
                'refresh_token' => $infst->oauth2_refresh_token,
                'expires_in' => $infst->expires_at
            ]
        );

        $infusionsoft = new InfusionsoftSdk([
            'clientId'     => getenv('INFSFT_INDENTIFIER'),
            'clientSecret' => getenv('INFSFT_SECRET'),
            'redirectUri'  => 'http://rozae.dev/oauth/callback/infusionsoft',
        ]);

        $infusionsoft->setToken($infstToken);

        try {

            $tags = $infusionsoft->data->query(
                'ContactGroup', 1000, 0, ['id' => '%'], ['Id', 'GroupName'], 'Id', true
            );

        } catch(\Infusionsoft\TokenExpiredException $e) {

            $infusionsoft->refreshAccessToken();
            $infstToken = $infusionsoft->getToken();

            $infst->oauth2_access_token  =  $infstToken->getAccessToken();
            $infst->oauth2_refresh_token =  $infstToken->getRefreshToken();
            $infst->oauth2_expires       =  $infstToken->getEndOfLife();

            $infst->save();

            $tags = $infusionsoft->data->query(
                'ContactGroup', 1000, 0, ['id' => '%'], ['Id', 'GroupName'], 'Id', true
            );

        }

**Comment by kressaty** [comment]
If you're getting the token expired exception on every request, the token is probably not being set properly after authorizing. I'm not sure what your first line is doing (looks like storage?) but as a start I'd recommend storing the entire Infusionsoft Token object a as a serialized PHP object rather than storing the pieces individually - that should reduce risk of error. Email me jonathan [at] vuurr [dot] com

**Comment by franciscocorrales** [comment]
+1 on this....

`[status code] 401
[reason phrase] Unauthorized`

Do I have to send some headers ?

**Comment by kressaty** [comment]
Check out the updated docs on this - 

@franciscocorrales  when you do request a refresh token, you need to pass an auth header: https://developer.infusionsoft.com/docs/xml-rpc/#authentication-refresh-an-access-token

@merlindiavova let me know where you're at on this

**Comment by kressaty** [comment]
@merlindiavova if you have no update on this, I'm going to mark it as closed. Definitely let me know if you have further issues!

**Comment by marceux** [comment]
Hello @kressaty ,

We are having the same 400 status code issue.  We set-up a runscope account to view what the issue may be.

The response we keep getting back is `{ "error": "invalid_grant", "error_description": "Invalid refresh token"}` and we think it has to do with the refresh token because my teammate is accessing the InfusionSoft API with the exact same methods.

Can I send you the public Runscope link?  Let me know!

**Comment by kressaty** [comment]
Are you and your teammate both using the same client id?

**Comment by marceux** [comment]
Yep.  We are.

**Comment by kressaty** [comment]
And there's no possible way you could be having collisions in refreshing the token? Once one of you does it, the other's would be invalidated.

The reason I ask is nothing has changed in the API, and nothing has changed in the SDK, which means it's 99% probable that the issue is somewhere between the SDK requesting the token and it being saved on your end.

**Comment by marceux** [comment]
Thanks for responding so quickly.  **I appreciate it.**

When you mention collisions refreshing the token, can this happen?  What are the scenarios that would create a collision and what exactly *is* a collision?

We have one Infusionsoft Developer account, and we created one application that we both use (client ID AND client secret). We authenticated the app using our own Infusionsoft credentials, and we have different refresh tokens. Would this cause a token collision? Or is this set-up ok? Should we have a different one?

Thanks!

**Comment by kressaty** [comment]
Whenever you're granted a refresh token, the other is going to be invalidated. So if you're both deving on different machines, you're going to be constantly refreshing tokens and fighting each other for the newest token. Most of the time this should take care of itself, but if you fail to refresh to hit it simultaneously it can cause problems.

I'd recommend just grabbing another client id by setting up another app in your developer account and each having one - that way you can isolate that as an issue and continue to debug the problem.

**Comment by marceux** [comment]
Thanks @kressaty.

But that begs the question: what if we're using a client id and client secret for one application that is being served publicly to folks without Infusionsoft accounts?

From your description, it sounds like this is the ideal

`Application -> ID + Secret -> One Environment -> One User`

where as we're using it like this...

`Application -> ID + Secret -> One Environment -> Many (Potentially Concurrent) Users`

**Comment by kressaty** [comment]
No, I'm implying per app. If you and another engineer are on two different machines building your app, that's two "apps". You should only have one client id/secret for your production app.

Are you having the issue in production or just locally?

**Comment by marceux** [comment]
Just locally. Production is working fine.

**Comment by sylviadantonio** [comment]
Hi! I have the same problem, I can't find help anywhere. I jason_encode and decode the token (is in session because is just a test)
I do it in the constructor of the class:
if (isset($_SESSION['token'])) {
			$tok = json_decode($_SESSION['token']);
			$this->infusionsoft->setToken(new \Infusionsoft\Token(array(					
					'access_token' => $tok->accessToken,
					'refresh_token' => $tok->refreshToken,
					'expires_in' => $tok->endOfLife,
					'extraInfo' => $tok->extraInfo
				)));
		} 

to use it I just :
$infusionObj->getInfustionSoft()->refreshAccessToken();
	$result = $infusionObj->getInfustionSoft()->data()->findByField('ContactGroupAssign', 1000, 0, 'GroupId', 130, $fields);

I get the same error:

object(Infusionsoft\Http\HttpException)#34 (7) { ["message":protected]=> string(2343) "exception 'GuzzleHttp\Exception\ClientException' with message 'Client error: `POST https://api.infusionsoft.com/token` resulted in a `400 Bad Request` response ....
Infusionsoft\Http\GuzzleHttpClient" ["type"]=> string(2) "->" ["args"]=> array(3) { [0]=> &string(4) "POST" [1]=> &string(34) "https://api.infusionsoft.com/token" [2]=> &array(2) { ["body"]=> string(63) "grant_type=refresh_token&refresh_token=xxxxxxxxxxx" ["headers"]=> array(2) { ["Authorization"]=> string(54) "Basic xxxxxxxxxxxxxxxxxxx=" ["Content-Type"]=> string(33) "application/x-www-form-urlencoded" } } } } [1]=> array(6) { ["file"]=> string(54) "/home/xxxxxxxxx/www/teste-infusion-dadada/index.php" ["line"]=> int(22) ["function"]=> string(18) "refreshAccessToken" ["class"]=> string(25) "Infusionsoft\Infusionsoft" ["type"]=> string(2) "->" ["args"]=> array(0) { } } } ["previous":"Exception":private]=> NULL }

(I replaced some info for xxxx)
I've tried several different things, but all finish the same way.
When I do a var_dump in the object $infusionObj->getInfustionSoft() is perfectly populated, the tokens, all the connection info, everything seems fine... 

Did anybody find a solution?

**Comment by SkywarpEvans** [comment]
I'm also still having the same issue. I would pay someone a lot of money to resolve this!!!!

**Comment by ismailiiui** [comment]
The problem is, when you authorize the app very first time and save the token in session and after that you refresh the accesstoken. The server grants you a new refreshtoken but you are not saving the most recent token in DB or session. Everytime you refresh the token, you must also pull the token and update your database with new refreshed token.

What I have done is, I created two files, one to deserealize the token and create object for my application to use and another script which runs every hour and refreshes the token and saves the token after it is refreshed.
