### ISSUE TITLE
Creating a Company using XML-RPC

### ISSUE THREAD

**Issue by bretto36** [infusionsoft/infusionsoft-php#165]
Is it possible to create a Company through this SDK? Or would we need new end points added?

**Comment by dkaitou** [comment]
Hi @bretto36 

Have you got the solution for creating company ?  

I guess you can use Data service to create Company.
- https://developer.infusionsoft.com/docs/xml-rpc/#data-create-a-record

The table name you will need to use is here
- https://developer.infusionsoft.com/docs/table-schema/

I got this issue too and trying to use above way to resolve it. 

Good luck

**Comment by dkaitou** [comment]
Hi @bretto36 

Did your resolve that by using same SDK ? 

I was trying to use function data() from this SDK but keep getting errors.
`infusionsoft->data()->add('Company', $companyName);`

Error shows: "No method matching arguments"

Kind regards

**Comment by dkaitou** [comment]
For anyone who is looking for the solution on DataService.I have got this sorted. Here is the example. 

The problem is caused by the my variable $companyName.

It used to be:
`$companyName = "Test company name"; ` 
`infusionsoft->data()->add('Company', $companyName);`
That needs to be:
`$companyName = ['Company'=>'Test company name'];  `
`infusionsoft->data()->add('Company', $companyName);`

Regards
