### ISSUE TITLE
performance problems while checking and add/update contacts 

### ISSUE THREAD

**Issue by olissongs** [infusionsoft/infusionsoft-php#185]
Hello,

im using this frameworki with yii2. Everthing ist working but i have bad response time from InfusionSoft

    `try {
            //$email = $model->email;//'john.doe4@example.com';
            try {
                \Yii::beginProfile('block-is-2a');
                $cid = $this->isSoft->contacts()->where('email', $model->email)->first();//$email)->first();
       
                \Yii::endProfile('block-is-2a');
                \Yii::beginProfile('block-is-2b');
                $arrID = ['id' => $cid->id];
                $kontakt = array_merge($arrID,$kontakt);
                $cid = $this->isSoft->contacts()->mock($kontakt)->save();
                \Yii::endProfile('block-is-2b');
          
            } catch (\Infusionsoft\InfusionsoftException $e) {
                \Yii::beginProfile('block-is-3');
             
                $cid = $this->isSoft->contacts()->mock($kontakt)->save();
               
                \Yii::endProfile('block-is-3');
            }

        } catch (\Infusionsoft\TokenExpiredException $e) {
          
            $retToken = $this->updateToken($token);
            if (isset($retToken)) {
           
                $cid = $this->isSoft->contacts()->mock($kontakt)->save();
           
            } 

        }`

My Profilung times:

18:19:40.872 | 2938.8 ms | application | →→→block-is-1
-- | -- | -- | --
18:19:42.159 | 1651.7 ms | application | →→→→block-is-2b // make the update to is
18:19:40.872 | 1287.1 ms | application | →→→→block-is-2a  // checks if contact exists

Is the Api so slow or do i use the wrong commands?

**Comment by brumiser1550** [comment]
Not IFS but use the API a lot. I constantly see times anywhere from milliseconds to 1,2, and even 3 seconds long. It really depends on the app that you are in. For instance, if your contact ids are really high numbers like in the 100K+, even if that many contacts don't exist, it will slow all the calls down because contacts are only soft deleted from the database. 

Try opening your network tab in dev tools and making the same call from [here ](https://developer.infusionsoft.com/docs/rest/#!/Contact/listContactsUsingGET) and see how long it takes. If it takes a similar amount of time then you are probably just going to be stuck that way and if not, you might have a bottle neck in your platform somewhere.

**Comment by brumiser1550** [comment]
The REST client should give you all the header information at the bottom of the result. The only thing you really need is a valid token and everything should work if you send the right data type. You can also get what headers are being sent from your network tab.

**Comment by olissongs** [comment]
ok changed it to curl, runs better using put for contact creating and updating
