### ISSUE TITLE
Build fail

### ISSUE THREAD

**Issue by odoremieux** [infusionsoft/infusionsoft-php#45]
When trying to follow the steps it fails. Also the build status on on the project page says error.

Here is what I get

composer require infusionsoft/php-sdk
Using version ^1.1 for infusionsoft/php-sdk
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - The requested package infusionsoft/php-sdk No version set (parsed as 1.0.0) could not be found.

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your minimum-stability setting
   see <https://groups.google.com/d/topic/composer-dev/_g3ASeIFlrc/discussion> for more details.

Read <https://getcomposer.org/doc/articles/troubleshooting.md> for further common problems.

Installation failed, reverting ./composer.json to its original content.

**Comment by kressaty** [comment]
Strange... you're not having other composer issues? That release still exists, and loaded fine for me.

**Comment by prinf** [comment]
@kressaty 
Similar issue I have, I think you should update dependencies to use guzzlehttp/guzzle instead of guzzle/guzzle:

Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for infusionsoft/php-sdk 1.1.1 -> satisfiable by infusionsoft/php-sdk[1.1.1].
    - infusionsoft/php-sdk 1.1.1 requires guzzle/guzzle 3.8.* -> no matching package found.

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your minimum-stability setting
