### ISSUE TITLE
Call to a member function getRefreshToken() on a non-object

### ISSUE THREAD

**Issue by rahul7777yadav** [infusionsoft/infusionsoft-php#52]
My code :
$infusionsoft = new InfusionsoftInfusionsoft(array(
    'clientId' => 'CLIENT_ID',
    'clientSecret' => 'CLIENT_SECRET',
    'redirectUri' => 'REDIRECT_URL',
));

// retrieve the existing token object from storage
$infusionsoft->setToken($yourStoredToken);

$infusionsoft->refreshAccessToken(); // this function create error.

refreshAccessToken function is following:

 public function refreshAccessToken()
    {
		$headers = array(
			'Authorization' => 'Basic ' . base64_encode($this->clientId . ':' . $this->clientSecret),
		);

        $params = array(
            'grant_type'    => 'refresh_token',
            'refresh_token' => $this->getToken()->getRefreshToken(),
        );

        $client = $this->getHttpClient();

        $tokenInfo = $client->request($this->tokenUri, $params, $headers, 'POST');

        $this->setToken(new Token($tokenInfo));

        return $this->getToken();
    }

Error is Following : 

Call to a member function getRefreshToken() on a non-object

**Comment by kressaty** [comment]
Without further insight into your code, it's hard to debug this. Most people with this issue end up having stored the token incorrectly - make sure it's an instance of InfusionsoftToken and that it's being pulled out of your storage mechanism properly.

You can always open a support request at https://developer.infusionsoft.com/support/tickets/create/

Closing due to non-code issue.

**Comment by itksandeep** [comment]
Fatal error: Call to a member function getRefreshToken() on a non-object in Infusionsoft.php on line 266
