### ISSUE TITLE
Call to undefined method stdClass::getRefreshToken() 

### ISSUE THREAD

**Issue by thedangler** [infusionsoft/infusionsoft-php#73]
$token = serialize(json_decode('{"access_token":"****","token_type":"bearer","expires_in":28800,"refresh_token":"","scope":"|****.infusionsoft.com"}'));

$infusion = new \Infusionsoft\Infusionsoft([
   'clientId' => '******',
    'clientSecret' => '******',
    'redirectUri' => 'www.example.com',
]);

$infusion->setToken(unserialize($token));

$infusion->refreshAccessToken(); // causing error

$contact = $infusion->contacts()->findByEmail('****@hotmail.com',['FirstName','LastName']);

var_dump($contact);

whats the deal?

**Comment by kressaty** [comment]
What's your question? "what's the deal?" doesn't describe the issue you're having or how to reproduce it. If your issue is that the token is not working after restoring it, 99% of the time it means it was stored incorrectly. you shouldn't be json decoding it and then serializing it, since you're not re-json encoding it and the setToken method expects an instance of InfusionsoftToken.

**Comment by thedangler** [comment]
I got the json token object from using that site you referred me too so the process isn't exactly like the instructions how do I create a infusionsoftToken from the json string?

**Comment by claytonfbell** [comment]
I'm brand new to this but I had same issue and figured out that I needed to create a new `\Infusionsoft\Token` object using array of values.

`$infusion->setToken(new \Infusionsoft\Token((array) unserialize($token)));`

**Comment by kressaty** [comment]
@claytonfbell is correct, you need to instantiate a new Infusionsoft\Token object

**Comment by ismailiiui** [comment]
When I set token with new keyword, it messes up token for example it appends token with null null values

**Comment by ismailiiui** [comment]
It looks like when we JSON decode the Token object, it no longer remains Token but appears as an array. Since there is no easy way to cast array to an object in PHP, I initialized new token and then another problem arises, which was the construct data names were mismatched to the JSON decoded array. So I created another array to match the names and voila.
Here is the solution:


$temptoken = json_decode($tokentoken,true);
$newtoken = array('access_token' =>$temptoken['accessToken'],
'refresh_token' =>$temptoken['refreshToken'],
'expires_in' =>$temptoken['endOfLife'] - time(),
'extraInfo' =>$temptoken['extraInfo']);

$tokentoset = new \Infusionsoft\Token($newtoken);
// var_dump($tokentoset);
$infusionsoft->setToken($tokentoset);
