### ISSUE TITLE
Rest API caches service classes

### ISSUE THREAD

**Issue by mattmerrill** [infusionsoft/infusionsoft-php#81]
The new REST Api classes get cached in the Infusionsoft instance, so any subsequent queries inherit previous query parameters.

For example, I instantiate a new Infusionsoft instance: `$infusionsoft`

Here is what happens:

``` php
// This is fine
$contactTransactions = $infusionsoft->transactions()->where('contact_id', 1)->get();
// Generates the following request: 
// https://api.infusionsoft.com/crm/rest/v1/transactions?access_token=TOKEN&contact_id=1

// But when I go to run a new query, it inherits the previous queries params:
$transactionsThisMonth = $infusionsoft->transactions()->where('since', '2016-07-01T00:00:00.000Z')->get()
// Generates the following request: 
// https://api.infusionsoft.com/crm/rest/v1/transactions?access_token=TOKEN&since=2016-07-01T00%3A00%3A00Z&contact_id=1
```

In my opinion, each call to `$infusionsoft->transaction()` should return a new instance of the transaction service object so that query params aren't 'cached'.

**Comment by mattmerrill** [comment]
By the way, I'm happy to submit a pull request if you approve the change

**Comment by KelseySheely** [comment]
We just noticed this issue with the Resthooks.  If you send a call to get all the available events ($infusionsoft->resthooks()->events()), then the returned object's attributes is filled with an array of events, which is then sent in with any subsequent calls, which in turn causes a 400.

It would make sense for the events() method to return a collection or simply an array rather than filling the object, but seeing that the issue does seem to affect all the Models, I do agree it would make more sense to just return a new instance every time rather than 'caching' the object.  

Another option would be to add a parameter to the getRestApi() method to not cache it, then have methods like the events() method send in that parameter.
