### ISSUE TITLE
CLI only

### ISSUE THREAD

**Issue by MACscr** [infusionsoft/infusionsoft-php#97]
I am not sure how I am supposed to use oath when my application is cli only. The infusionsoft user only supplies us with the app id/pass or api-key. Any suggestions? Seems this appears to be made for only web based access to it.

**Comment by micfai** [comment]
Only the initial authorization needs a UI. You can use https://www.runscope.com/oauth2_tool to generate a token, after that it can be refreshed without user interaction.

**Comment by MACscr** [comment]
Well its CLI only, so that's not going to work and dont want to use a third party like that. Seems I am going to have to roll my own solution to work with the older api key method. Has there been a published EOL for the api key auth option?

**Comment by bgpartridge** [comment]
@MACscr we are currently looking at expanding our supported OAuth flows but to date do not support a purely non web based approach. There has not been a published EOL for the api key, that will be coming in 2017 after we have a few more solutions in place to make transition easier.  To be clear, that doesn't mean it will be EOL'd in 2017, it means that the timeline will be published in 2017.

**Comment by KelseySheely** [comment]
@MACscr if you have access to a web server of any kind, you can create a simple script in order to create an authorization and generate a token which you can store using the script. Once you generate and store that token (as documented in the Authentication section of the Readme), you can use it in your CLI scripts. Granted this is a bit more complicated than the simple API Key authentication, but it should work for you.

**Comment by MACscr** [comment]
@KelseySheely thanks for the idea. I am just using the api key method though. Have no interest in doing hacks/workarounds for oauth. I understand the point of oath for frontend integration, but makes zero sense for automated tasks.

**Comment by igorsantos07** [comment]
I reopened this request through #191 as this problem is still a thing, and there's an accepted standard to solve this: OOB flows, such as those implemented by Google, Twitter and Asana (the flow ends in a copy-paste screen). At least it drops the need for a seldom-used web server without third-party tools.
